import commonString from '../../../utils/String'

export const employeForm = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commonString.user_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.user_id}`,
    required: `${commonString.Please_enter} ${commonString.user_id}`,
    placeholder: `${commonString.enter} ${commonString.user_id}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commonString.role_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.role_id}`,
    required: `${commonString.Please_enter} ${commonString.role_id}`,
    placeholder: `${commonString.enter} ${commonString.role_id}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commonString.created_by}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.created_by}`,
    required: `${commonString.Please_enter} ${commonString.created_by}`,
    placeholder: `${commonString.enter} ${commonString.created_by}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commonString.updated_by}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.updated_by}`,
    required: `${commonString.Please_enter} ${commonString.updated_by}`,
    placeholder: `${commonString.enter} ${commonString.updated_by}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commonString.code}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.code}`,
    required: `${commonString.Please_enter} ${commonString.code}`,
    placeholder: `${commonString.enter} ${commonString.code}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commonString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.status}`,
    option: [
      { value: `${commonString.active}`, label: `${commonString.active}` },
      { value: `${commonString.pending}`, label: `${commonString.pending}` },
      { value: `${commonString.suspend}`, label: `${commonString.suspend}` },
    ],
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commonString.start_at}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.start_att}`,
    required: `${commonString.Please_enter} ${commonString.start_at}`,
    placeholder: `${commonString.enter} ${commonString.start_at}`,
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commonString.end_at}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.end_at}`,
    required: `${commonString.Please_enter} ${commonString.end_at}`,
    placeholder: `${commonString.enter} ${commonString.end_at}`,
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commonString.note}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.note}`,
    required: `${commonString.Please_enter} ${commonString.note}`,
    placeholder: `${commonString.enter} ${commonString.note}`,
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commonString.is_active}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commonString.active}`, label: `${commonString.active}` },
      { value: `${commonString.inactive}`, label: `${commonString.inactive}` },
    ],
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: `${commonString.is_delete}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      {
        value: `${commonString.is_delete}`,
        label: `${commonString.is_delete}`,
      },
      {
        value: `${commonString.is_not_deleted}`,
        label: `${commonString.is_not_deleted}`,
      },
    ],
  },
]

export const employeTable = [
  {
    id: 1,
    name: 'User Id',
    className: `${commonString.sub_text}`,
  },
  {
    id: 2,
    name: `${commonString.role_id}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 3,
    name: `${commonString.created_by}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 4,
    name: `${commonString.updated_by}`,
    className: `${commonString.sub_text}`,
  },

  {
    id: 6,
    name: `${commonString.code}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 7,
    name: `${commonString.status}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 8,
    name: `${commonString.is_active}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 9,
    name: `${commonString.is_delete}`,
    className: `${commonString.sub_text}`,
  },
]
