import commanString from '../../../utils/String'

export const employeForm = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.user_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.user_id}`,
    required: `${commanString.Please_enter} ${commanString.user_id}`,
    placeholder: `${commanString.enter} ${commanString.user_id}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.role_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.role_id}`,
    required: `${commanString.Please_enter} ${commanString.role_id}`,
    placeholder: `${commanString.enter} ${commanString.role_id}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.created_by}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.created_by}`,
    required: `${commanString.Please_enter} ${commanString.created_by}`,
    placeholder: `${commanString.enter} ${commanString.created_by}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.updated_by}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.updated_by}`,
    required: `${commanString.Please_enter} ${commanString.updated_by}`,
    placeholder: `${commanString.enter} ${commanString.updated_by}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.code}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.code}`,
    required: `${commanString.Please_enter} ${commanString.code}`,
    placeholder: `${commanString.enter} ${commanString.code}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.status}`,
    option: [
      { value: `${commanString.active}`, label: `${commanString.active}` },
      { value: `${commanString.pending}`, label: `${commanString.pending}` },
      { value: `${commanString.suspend}`, label: `${commanString.suspend}` },
    ],
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commanString.start_at}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.start_att}`,
    required: `${commanString.Please_enter} ${commanString.start_at}`,
    placeholder: `${commanString.enter} ${commanString.start_at}`,
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commanString.end_at}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.end_at}`,
    required: `${commanString.Please_enter} ${commanString.end_at}`,
    placeholder: `${commanString.enter} ${commanString.end_at}`,
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commanString.note}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.note}`,
    required: `${commanString.Please_enter} ${commanString.note}`,
    placeholder: `${commanString.enter} ${commanString.note}`,
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commanString.isactive}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.active}`, label: `${commanString.active}` },
      { value: `${commanString.inactive}`, label: `${commanString.inactive}` },
    ],
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: `${commanString.isdelete}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.isdelete}`, label: `${commanString.isdelete}` },
      {
        value: `${commanString.is_not_deleted}`,
        label: `${commanString.is_not_deleted}`,
      },
    ],
  },
]

export const employeTable = [
  {
    id: 1,
    name: 'User Id',
    className: `${commanString.sub_text}`,
  },
  {
    id: 2,
    name: `${commanString.role_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 3,
    name: `${commanString.created_by}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 4,
    name: `${commanString.updated_by}`,
    className: `${commanString.sub_text}`,
  },

  {
    id: 6,
    name: `${commanString.code}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 7,
    name: `${commanString.status}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 8,
    name: `${commanString.isactive}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 9,
    name: `${commanString.isdelete}`,
    className: `${commanString.sub_text}`,
  },
]
