import String from '../../../utils/String'

export const userInfo = [
  {
    id: 1,
    name: `${String.avatar}`,
  },
  {
    id: 2,
    name: `${String.email}`,
  },
  {
    id: 3,
    name: `${String.mobile_number}`,
  },
  {
    id: 4,
    name: '',
  },
]

export const userCreate = [
  {
    id: 1,
    label_name: `${String.first_name}`,
    type: 'text',
    name: `${String.first_name}`,
    placeholder: `${String.enter} ${String.first_name}`,
    required: 'Required *',
    key_name: 'firstName',
  },
  {
    id: 2,
    label_name: `${String.middle_name}`,
    type: 'text',
    name: `${String.middle_name}`,
    placeholder: `${String.enter} ${String.middle_name}`,
    key_name: 'middleName',
  },
  {
    id: 3,
    label_name: `${String.last_name}`,
    type: 'text',
    name: `${String.last_name}`,
    placeholder: `${String.enter} ${String.last_name}`,
    required: 'Required *',
    key_name: 'lastName',
  },
  {
    id: 4,
    label_name: `${String.employee_code}`,
    type: 'text',
    name: `${String.employee_code}`,
    placeholder: `${String.enter} ${String.employee_code}`,
    required: 'Required *',
    key_name: 'employeeCode',
  },
  {
    id: 5,
    label_name: `${String.company_email}`,
    type: 'email',
    name: `${String.company_email}`,
    placeholder: `${String.enter} ${String.company_email}`,
    required: 'Required *',
    key_name: 'companyEmail',
  },
  {
    id: 6,
    label_name: `${String.employment} ${String.status}`,
    type: 'select',
    name: `${String.employment} ${String.status}`,
    state_name: 'empStatus',
    required: 'Required *',
    key_name: 'employmentStatus',
  },
  {
    id: 7,
    label_name: `${String.department}`,
    type: 'select',
    name: `${String.department}`,
    state_name: 'department',
    required: 'Required *',
    key_name: 'department',
  },
  {
    id: 8,
    label_name: `${String.designation}`,
    type: 'select',
    name: `${String.designation}`,
    state_name: 'designation',
    required: 'Required *',
    key_name: 'designation',
  },
  {
    id: 9,
    label_name: `${String.manager_team_lead}`,
    type: 'select',
    name: `${String.manager_team_lead}`,
    state_name: 'teamLead',
    key_name: 'teamLead',
    // required: 'Required *',
  },
  {
    id: 10,
    label_name: `${String.joining_date}`,
    type: 'date',
    name: `${String.joining_date}`,
    required: 'Required *',
    key_name: 'joiningDate',
  },
  {
    id: 11,
    label_name: `${String.onboarding_date}`,
    type: 'date',
    name: `${String.onboarding_date}`,
    required: 'Required *',
    key_name: 'onboardingDate',
  },
  {
    id: 12,
    label_name: `${String.relieving_date}`,
    type: 'date',
    name: `${String.relieving_date}`,
    required: 'Required *',
    key_name: 'relievingDate',
  },
  {
    id: 13,
    label_name: `${String.birth_day}`,
    type: 'date',
    name: `${String.birth_day}`,
    required: 'Required *',
    max: new Date().toISOString().split('T')[0],
    key_name: 'birthDate',
  },
  {
    id: 14,
    label_name: `${String.nationality}`,
    type: 'select',
    name: `${String.nationality}`,
    state_name: 'nationality',
    required: 'Required *',
    key_name: 'nationality',
  },
  {
    id: 15,
    label_name: `${String.blood_group}`,
    type: 'select',
    name: `${String.blood_group}`,
    state_name: 'bloodGroup',
    required: 'Required *',
    key_name: 'bloodGroup',
  },
  {
    id: 16,
    label_name: `${String.gender}`,
    type: 'select',
    name: `${String.gender}`,
    state_name: 'gender',
    required: 'Required *',
    key_name: 'gender',
  },
  {
    id: 17,
    label_name: `${String.personal_email}`,
    type: 'email',
    name: `${String.personal_email}`,
    required: 'Required *',
    placeholder: `${String.Please_enter} ${String.personal_email}`,
    key_name: 'personalEmail',
  },
  {
    id: 18,
    label_name: `${String.mobile_number}`,
    type: 'number',
    name: `${String.mobile_number}`,
    validationType: 'mobile-number',
    validationMessage: `${String.Please_enter} ${String.valid} ${String.mobile_number}`,
    required: 'Required *',
    placeholder: `${String.Please_enter} ${String.mobile_number}`,
    key_name: 'mobileNumber',
  },
  {
    id: 19,
    label_name: `${String.whatsapp_mobile}`,
    type: 'number',
    name: `${String.whatsapp_mobile}`,
    validationType: 'mobile-number',
    validationMessage: `${String.Please_enter} ${String.valid} ${String.whatsapp_mobile}`,
    placeholder: `${String.Please_enter} ${String.whatsapp_mobile}`,
    required: 'Required *',
    key_name: 'whatsappNumber',
  },
  {
    id: 20,
    label_name: `${String.parent_mobile}`,
    type: 'number',
    name: `${String.parent_mobile}`,
    validationType: 'mobile-number',
    validationMessage: `${String.Please_enter} ${String.valid} ${String.parent_mobile}`,
    required: 'Required *',
    placeholder: `${String.Please_enter} ${String.parent_mobile}`,
    key_name: 'parentsMobileNumber',
  },
  {
    id: 21,
    label_name: `${String.aadhaar_card_number}`,
    type: 'text',
    validationType: 'aadhaar-card-number',
    validationMessage: `${String.Please_enter} ${String.valid} ${String.aadhaar_card_number}`,
    name: `${String.aadhaar_card_number}`,
    placeholder: `${String.Please_enter} ${String.aadhaar_card_number}`,
    required: 'Required *',
    key_name: 'aadharCard',
  },
  {
    id: 22,
    label_name: `${String.pan_card_number}`,
    type: 'text',
    validationType: 'pan-card-number',
    validationMessage: `${String.Please_enter} ${String.valid} ${String.pan_card_number}`,
    name: `${String.pan_card_number}`,
    placeholder: `${String.Please_enter} ${String.pan_card_number}`,
    required: 'Required *',
    key_name: 'panCard',
  },
]

export const AddressDetailForm = [
  {
    id: 1,
    label_name: `${String.address_1}`,
    type: 'text',
    name: `${String.address_1}`,
    placeholder: `${String.enter} ${String.address_1}`,
    required: 'Required *',
    key_name: 'address1',
  },
  {
    id: 2,
    label_name: `${String.address_2}`,
    type: 'text',
    name: `${String.address_2}`,
    placeholder: `${String.enter} ${String.address_2}`,
    required: 'Required *',
    key_name: 'address2',
  },
  {
    id: 6,
    label_name: `${String.country}`,
    type: 'select',
    name: `${String.country}`,
    state_name: 'countries',
    placeholder: `${String.enter} ${String.country}`,
    required: 'Required *',
    key_name: 'country',
  },
  {
    id: 5,
    label_name: `${String.state_region}`,
    type: 'select',
    name: `${String.state_region}`,
    state_name: 'states',
    placeholder: `${String.enter} ${String.state_region}`,
    required: 'Required *',
    key_name: 'state',
  },
  {
    id: 3,
    label_name: `${String.city}`,
    type: 'select',
    name: `${String.city}`,
    state_name: 'city',
    placeholder: `${String.enter} ${String.city}`,
    required: 'Required *',
    key_name: 'city',
  },
  {
    id: 6,
    label_name: `${String.postal_code}`,
    type: 'number',
    name: `${String.postal_code}`,
    placeholder: `${String.enter} ${String.postal_code}`,
    required: 'Required *',
    key_name: 'zipCode',
  },
]

export const tableHeader = [
  {
    id: '',
    type: '',
    header: '',
  },
  {
    id: 'c1',
    type: 'checkbox',
    header: 'View',
  },
  {
    id: 'c2',
    type: 'checkbox',
    header: 'Add',
  },
  {
    id: 'c3',
    type: 'checkbox',
    header: 'Edit',
  },
  {
    id: 'c4',
    type: 'checkbox',
    header: 'Delete',
  },
]

export const tableRow = [
  {
    id: 'r1',
    name: 'Leave',
    type: 'checkbox',
  },
  {
    id: 'r2',
    name: 'Holiday',
    type: 'checkbox',
  },
  {
    id: 'r3',
    name: 'Asset',
    type: 'checkbox',
  },
  {
    id: 'r3',
    name: 'Company Doc',
    type: 'checkbox',
  },
  {
    id: 'r3',
    name: 'Company Policy',
    type: 'checkbox',
  },
]
