import commanString from '../../../utils/CommanString'

export const userInfo = [
  {
    id: 1,
    name: `${commanString.avatr}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 2,
    name: `${commanString.first_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 3,
    name: `${commanString.last_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 4,
    name: `${commanString.role_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.department}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.mobile}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.email}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 7,
    name: `${commanString.registered_at}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 8,
    name: `${commanString.isactive}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 9,
    name: `${commanString.isdelete}`,
    className: `${commanString.sub_text}`,
  },
]

export const personalField = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.first_name}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.first_name}`,
    placeholder: `${commanString.enter} ${commanString.first_name}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.last_name}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.last_name}`,
    placeholder: `${commanString.enter} ${commanString.last_name}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.gender}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.gender}`,
    option: [
      { value: `${commanString.male}`, label: `${commanString.male}` },
      { value: `${commanString.female}`, label: `${commanString.female}` },
    ],
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.birth_day}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.birth_day}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.department}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.department}`,
    placeholder: `${commanString.enter} ${commanString.department}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.role}`,
    input_class: 'form-control',
    type: 'select',
    option: [
      { value: `${commanString.admin}`, label: `${commanString.admin}` },
      { value: `${commanString.user}`, label: `${commanString.user}` },
    ],
  },
]

export const personalDetailField = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.current_address}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.current_address}`,
    placeholder: `${commanString.enter} ${commanString.current_address}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.permenent_address}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.permenent_address}`,
    placeholder: `${commanString.enter} ${commanString.permenent_address}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.education}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.education}`,
    placeholder: `${commanString.enter} ${commanString.education}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.country}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.country}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.height}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.height}`,
    placeholder: `${commanString.enter} ${commanString.height}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.status}`,
    option: [
      { value: `${commanString.active}`, label: `${commanString.active}` },
      { value: `${commanString.pending}`, label: `${commanString.pending}` },
      { value: `${commanString.suspend}`, label: `${commanString.suspend}` },
    ],
  },
]

export const numberEmailField = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commanString.email}`,
    placeholder: `${commanString.enter} ${commanString.email}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.personal_email}`,
    input_class: `${commanString.forms_control}`,
    type: 'email',
    name: `${commanString.personal_email}`,
    placeholder: `${commanString.enter} ${commanString.personal_email}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.mobile}`,
    placeholder: `${commanString.enter} ${commanString.mobile}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.parent_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.parent_mobile}`,
    placeholder: `${commanString.enter} ${commanString.parent_mobile}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.whatsapp_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.whatsapp_mobile}`,
    placeholder: `${commanString.enter} ${commanString.whatsapp_mobile}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.adhar_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.adhar_card_number}`,
    placeholder: `${commanString.enter} ${commanString.adhar_card_number}`,
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commanString.pan_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.pan_card_number}`,
    placeholder: `${commanString.enter} ${commanString.pan_card_number}`,
  },
]
export const officeDetailField = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.registered_at}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.registered_at}`,
    placeholder: `${commanString.enter} ${commanString.registered_at}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.last_login}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.last_login}`,
    placeholder: `${commanString.enter} ${commanString.last_login}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.profile}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.profile}`,
    placeholder: `${commanString.enter} ${commanString.profile}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.intro}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.intro}`,
    placeholder: `${commanString.enter} ${commanString.intro}`,
  },
]
export const otherDetailField = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.swift_time}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.swift_time}`,
    placeholder: `${commanString.enter} ${commanString.swift_time}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.isactive}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.active}`, label: `${commanString.active}` },
      { value: `${commanString.inactive}`, label: `${commanString.inactive}` },
    ],
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.isdelete}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.isdelete}`, label: `${commanString.isdelete}` },
      {
        value: `${commanString.is_not_deleted}`,
        label: `${commanString.is_not_deleted}`,
      },
    ],
  },
]
