import commonString from '../../../utils/String'

export const userInfo = [
  {
    id: 1,
    name: `${commonString.avatr}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 2,
    name: `${commonString.first_name}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 3,
    name: `${commonString.last_name}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 4,
    name: `${commonString.role_id}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 6,
    name: `${commonString.department}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 6,
    name: `${commonString.mobile}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 6,
    name: `${commonString.email}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 7,
    name: `${commonString.registered_at}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 8,
    name: `${commonString.is_active}`,
    className: `${commonString.sub_text}`,
  },
  {
    id: 9,
    name: `${commonString.is_delete}`,
    className: `${commonString.sub_text}`,
  },
]

export const userCreate = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commonString.first_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.first_name}`,
    placeholder: `${commonString.enter} ${commonString.first_name}`,
    required: '*',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commonString.middle_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.middle_name}`,
    placeholder: `${commonString.enter} ${commonString.middle_name}`,
    required: '*',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commonString.last_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.last_name}`,
    placeholder: `${commonString.enter} ${commonString.last_name}`,
    required: '*',
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commonString.employee_code}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.employee_code}`,
    placeholder: `${commonString.enter} ${commonString.employee_code}`,
    required: '*',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commonString.company_email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commonString.company_email}`,
    placeholder: `${commonString.enter} ${commonString.company_email}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commonString.employment} ${commonString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.employment} ${commonString.status}`,
    option: [
      {
        value: `${commonString.permanent}`,
        label: `${commonString.permanent}`,
      },
      { value: `${commonString.training}`, label: `${commonString.training}` },
      {
        value: `${commonString.ex_employee}`,
        label: `${commonString.ex_employee}`,
      },
    ],
    required: '*',
  },

  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commonString.department}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.department}`,
    option: [
      { value: `${commonString.admin}`, label: `${commonString.admin}` },
      { value: `${commonString.user}`, label: `${commonString.user}` },
    ],
    required: '*',
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commonString.designation}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.designation}`,
    option: [
      { value: `${commonString.admin}`, label: `${commonString.admin}` },
      { value: `${commonString.user}`, label: `${commonString.user}` },
      { value: `${commonString.hr}`, label: `${commonString.hr}` },
    ],
    required: '*',
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commonString.manager_team_lead}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.manager_team_lead}`,
    option: [
      {
        value: `${commonString.amit_kasetiya}`,
        label: `${commonString.amit_kasetiya}`,
      },
    ],
    required: '*',
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commonString.joining_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.joining_date}`,
    required: '*',
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: `${commonString.onboarding_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.onboarding_date}`,
  },
  {
    id: 12,
    label_class: 'form-label',
    label_name: `${commonString.relieving_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.relieving_date}`,
  },
  {
    id: 13,
    label_class: 'form-label',
    label_name: `${commonString.birth_day}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commonString.birth_day}`,
    required: '*',
    today: new Date().toISOString().split('T')[0],
  },
  {
    id: 14,
    label_class: 'form-label',
    label_name: `${commonString.nationality}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.nationality}`,
    required: '*',
  },
  {
    id: 15,
    label_class: 'form-label',
    label_name: `${commonString.blood_group}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.blood_group}`,
    required: '*',
    option: [
      { value: `${commonString.a}`, label: `${commonString.a}` },
      { value: `${commonString.a_plus}`, label: `${commonString.a_plus}` },
      { value: `${commonString.b}`, label: `${commonString.b}` },
      { value: `${commonString.b_plus}`, label: `${commonString.b_plus}` },
      { value: `${commonString.o}`, label: `${commonString.o}` },
      { value: `${commonString.o_plus}`, label: `${commonString.o_plus}` },
    ],
  },
  {
    id: 16,
    label_class: 'form-label',
    label_name: `${commonString.gender}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.gender}`,
    required: '*',
    option: [
      { value: `${commonString.male}`, label: `${commonString.male}` },
      { value: `${commonString.female}`, label: `${commonString.female}` },
    ],
  },

  {
    id: 17,
    label_class: 'form-label',
    label_name: `${commonString.personal_email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commonString.personal_email}`,
    required: '*',
    placeholder: `${commonString.Please_enter} ${commonString.personal_email}`,
  },
  {
    id: 18,
    label_class: 'form-label',
    label_name: `${commonString.mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.mobile}`,
    required: '*',
    placeholder: `${commonString.Please_enter} ${commonString.mobile}`,
  },
  {
    id: 19,
    label_class: 'form-label',
    label_name: `${commonString.whatsapp_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.whatsapp_mobile}`,
    placeholder: `${commonString.Please_enter} ${commonString.whatsapp_mobile}`,
  },
  {
    id: 20,
    label_class: 'form-label',
    label_name: `${commonString.parent_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.parent_mobile}`,
    required: '*',
    placeholder: `${commonString.Please_enter} ${commonString.parent_mobile}`,
  },
  {
    id: 21,
    label_class: 'form-label',
    label_name: `${commonString.adhar_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.adhar_card_number}`,
    placeholder: `${commonString.Please_enter} ${commonString.adhar_card_number}`,
  },
  {
    id: 22,
    label_class: 'form-label',
    label_name: `${commonString.pan_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.pan_card_number}`,
    placeholder: `${commonString.Please_enter} ${commonString.pan_card_number}`,
  },
]

export const AddressDetailform = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commonString.address_1}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.address_1}`,
    placeholder: `${commonString.enter} ${commonString.address_1}`,
    required: '*',
    permanent_address: 'Permanent Address',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commonString.address_2}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.address_2}`,
    placeholder: `${commonString.enter} ${commonString.address_2}`,
    required: '*',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commonString.city}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.city}`,
    placeholder: `${commonString.enter} ${commonString.city}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commonString.postal_code}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commonString.postal_code}`,
    placeholder: `${commonString.enter} ${commonString.postal_code}`,
    required: '*',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commonString.state_region}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commonString.state_region}`,
    placeholder: `${commonString.enter} ${commonString.state_region}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commonString.country}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commonString.country}`,
    placeholder: `${commonString.enter} ${commonString.country}`,
    required: '*',
    option: [
      { value: `${commonString.indian}`, label: `${commonString.indian}` },
    ],
  },
]

export const tableHeader = [
  {
    id: '',
    type: '',
    header: '',
  },
  {
    id: 'c1',
    type: 'checkbox',
    header: 'View',
  },
  {
    id: 'c2',
    type: 'checkbox',
    header: 'Add',
  },
  {
    id: 'c3',
    type: 'checkbox',
    header: 'Edit',
  },
  {
    id: 'c4',
    type: 'checkbox',
    header: 'Delete',
  },
]

export const tableRow = [
  {
    id: 'r1',
    name: 'Leave',
    type: 'checkbox',
  },
  {
    id: 'r2',
    name: 'Holiday',
    type: 'checkbox',
  },
  {
    id: 'r3',
    name: 'Asset',
    type: 'checkbox',
  },
]
