import commanString from '../../../utils/CommanString'

export const userInfo = [
  {
    id: 1,
    name: `${commanString.avatr}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 2,
    name: `${commanString.first_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 3,
    name: `${commanString.last_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 4,
    name: `${commanString.role_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.department}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.mobile}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.email}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 7,
    name: `${commanString.registered_at}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 8,
    name: `${commanString.isactive}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 9,
    name: `${commanString.isdelete}`,
    className: `${commanString.sub_text}`,
  },
]

export const userCreate = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.first_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.first_name}`,
    placeholder: `${commanString.enter} ${commanString.first_name}`,
    required: '*',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.middle_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.middle_name}`,
    placeholder: `${commanString.enter} ${commanString.middle_name}`,
    required: '*',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.last_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.last_name}`,
    placeholder: `${commanString.enter} ${commanString.last_name}`,
    required: '*',
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.employee_code}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.employee_code}`,
    placeholder: `${commanString.enter} ${commanString.employee_code}`,
    required: '*',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.company_email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commanString.company_email}`,
    placeholder: `${commanString.enter} ${commanString.company_email}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.employment} ${commanString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.employment} ${commanString.status}`,
    option: [
      {
        value: `${commanString.permanent}`,
        label: `${commanString.permanent}`,
      },
      { value: `${commanString.training}`, label: `${commanString.training}` },
      {
        value: `${commanString.ex_employee}`,
        label: `${commanString.ex_employee}`,
      },
    ],
    required: '*',
  },

  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commanString.department}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.department}`,
    option: [
      { value: `${commanString.admin}`, label: `${commanString.admin}` },
      { value: `${commanString.user}`, label: `${commanString.user}` },
    ],
    required: '*',
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commanString.designation}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.designation}`,
    option: [
      { value: `${commanString.admin}`, label: `${commanString.admin}` },
      { value: `${commanString.user}`, label: `${commanString.user}` },
      { value: `${commanString.hr}`, label: `${commanString.hr}` },
    ],
    required: '*',
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commanString.manager_team_lead}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.manager_team_lead}`,
    option: [
      {
        value: `${commanString.amit_kasetiya}`,
        label: `${commanString.amit_kasetiya}`,
      },
    ],
    required: '*',
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commanString.joining_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commanString.joining_date}`,
    required: '*',
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: `${commanString.onboarding_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commanString.onboarding_date}`,
  },
  {
    id: 12,
    label_class: 'form-label',
    label_name: `${commanString.relieving_date}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commanString.relieving_date}`,
  },
  {
    id: 13,
    label_class: 'form-label',
    label_name: `${commanString.birth_day}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commanString.birth_day}`,
    required: '*',
    today: new Date().toISOString().split('T')[0],
  },
  {
    id: 14,
    label_class: 'form-label',
    label_name: `${commanString.nationality}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.nationality}`,
    required: '*',
  },
  {
    id: 15,
    label_class: 'form-label',
    label_name: `${commanString.blood_group}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.blood_group}`,
    required: '*',
    option: [
      { value: `${commanString.a}`, label: `${commanString.a}` },
      { value: `${commanString.a_plus}`, label: `${commanString.a_plus}` },
      { value: `${commanString.b}`, label: `${commanString.b}` },
      { value: `${commanString.b_plus}`, label: `${commanString.b_plus}` },
      { value: `${commanString.o}`, label: `${commanString.o}` },
      { value: `${commanString.o_plus}`, label: `${commanString.o_plus}` },
    ],
  },
  {
    id: 16,
    label_class: 'form-label',
    label_name: `${commanString.gender}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.gender}`,
    required: '*',
    option: [
      { value: `${commanString.male}`, label: `${commanString.male}` },
      { value: `${commanString.female}`, label: `${commanString.female}` },
    ],
  },

  {
    id: 17,
    label_class: 'form-label',
    label_name: `${commanString.personal_email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commanString.personal_email}`,
    required: '*',
    placeholder: `${commanString.Please_enter} ${commanString.personal_email}`,
  },
  {
    id: 18,
    label_class: 'form-label',
    label_name: `${commanString.mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.mobile}`,
    required: '*',
    placeholder: `${commanString.Please_enter} ${commanString.mobile}`,
  },
  {
    id: 19,
    label_class: 'form-label',
    label_name: `${commanString.whatsapp_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.whatsapp_mobile}`,
    placeholder: `${commanString.Please_enter} ${commanString.whatsapp_mobile}`,
  },
  {
    id: 20,
    label_class: 'form-label',
    label_name: `${commanString.parent_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.parent_mobile}`,
    required: '*',
    placeholder: `${commanString.Please_enter} ${commanString.parent_mobile}`,
  },
  {
    id: 21,
    label_class: 'form-label',
    label_name: `${commanString.adhar_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.adhar_card_number}`,
    placeholder: `${commanString.Please_enter} ${commanString.adhar_card_number}`,
  },
  {
    id: 22,
    label_class: 'form-label',
    label_name: `${commanString.pan_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.pan_card_number}`,
    placeholder: `${commanString.Please_enter} ${commanString.pan_card_number}`,
  },
]

export const AddressDetailform = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.address_1}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.address_1}`,
    placeholder: `${commanString.enter} ${commanString.address_1}`,
    required: '*',
    permanent_address: 'Permanent Address',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.address_2}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.address_2}`,
    placeholder: `${commanString.enter} ${commanString.address_2}`,
    required: '*',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.city}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.city}`,
    placeholder: `${commanString.enter} ${commanString.city}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.postal_code}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.postal_code}`,
    placeholder: `${commanString.enter} ${commanString.postal_code}`,
    required: '*',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.state_region}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.state_region}`,
    placeholder: `${commanString.enter} ${commanString.state_region}`,
    required: '*',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.country}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.country}`,
    placeholder: `${commanString.enter} ${commanString.country}`,
    required: '*',
    option: [
      { value: `${commanString.indian}`, label: `${commanString.indian}` },
    ],
  },
]

export const tableHeader = [
  {
    id: '',
    type: '',
    header: '',
  },
  {
    id: 1,
    type: 'checkbox',
    header: 'View',
  },
  {
    id: 2,
    type: 'checkbox',
    header: 'Add',
  },
  {
    id: 3,
    type: 'checkbox',
    header: 'Edit',
  },
  {
    id: 4,
    type: 'checkbox',
    header: 'Delete',
  },
]

export const tableRow = [
  {
    id: 1,
    name: 'Leave',
    type: 'checkbox',
  },
  {
    id: 2,
    name: 'Holiday',
    type: 'checkbox',
  },
  {
    id: 3,
    name: 'Asset',
    type: 'checkbox',
  },
]
