import commanString from '../../../utils/CommanString'

export const userInfo = [
  {
    id: 1,
    name: `${commanString.avatr}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 2,
    name: `${commanString.first_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 3,
    name: `${commanString.last_name}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 4,
    name: `${commanString.role_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.department}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.mobile}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.email}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 7,
    name: `${commanString.registered_at}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 8,
    name: `${commanString.isactive}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 9,
    name: `${commanString.isdelete}`,
    className: `${commanString.sub_text}`,
  },
]

export const userCreate = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.first_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.first_name}`,
    placeholder: `${commanString.enter} ${commanString.first_name}`,
    required: `${commanString.Please_enter} ${commanString.first_name}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.middle_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.middle_name}`,
    placeholder: `${commanString.enter} ${commanString.middle_name}`,
    required: `${commanString.Please_enter} ${commanString.middle_name}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.last_name}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.last_name}`,
    placeholder: `${commanString.enter} ${commanString.last_name}`,
    required: `${commanString.Please_enter} ${commanString.last_name}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.employee_code}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.employee_code}`,
    placeholder: `${commanString.enter} ${commanString.employee_code}`,
    required: `${commanString.Please_enter} ${commanString.employee_code}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.designation}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.designation}`,
    option: [
      { value: `${commanString.admin}`, label: `${commanString.admin}` },
      { value: `${commanString.user}`, label: `${commanString.user}` },
      { value: `${commanString.hr}`, label: `${commanString.hr}` },
    ],
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.blood_group}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.blood_group}`,
    option: [
      { value: `${commanString.a}`, label: `${commanString.a}` },
      { value: `${commanString.a_plus}`, label: `${commanString.a_plus}` },
      { value: `${commanString.b}`, label: `${commanString.b}` },
      { value: `${commanString.b_plus}`, label: `${commanString.b_plus}` },
      { value: `${commanString.o}`, label: `${commanString.o}` },
      { value: `${commanString.o_plus}`, label: `${commanString.o_plus}` },
    ],
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commanString.department}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.department}`,
    option: [
      { value: `${commanString.admin}`, label: `${commanString.admin}` },
      { value: `${commanString.user}`, label: `${commanString.user}` },
    ],
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commanString.height}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.height}`,
    placeholder: `${commanString.enter} ${commanString.height}`,
    required: `${commanString.Please_enter} ${commanString.height}`,
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commanString.gender}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.gender}`,
    option: [
      { value: `${commanString.male}`, label: `${commanString.male}` },
      { value: `${commanString.female}`, label: `${commanString.female}` },
    ],
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commanString.nationality}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.nationality}`,
    option: [
      { value: `${commanString.indian}`, label: `${commanString.indian}` },
    ],
  },
  {
    id: 'datePickerId',
    label_class: 'form-label',
    label_name: `${commanString.birth_day}`,
    input_class: 'form-control',
    type: 'date',
    name: `${commanString.birth_day}`,
    max_date: 'new Date()',
  },
  {
    id: 12,
    label_class: 'form-label',
    label_name: `${commanString.mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.mobile}`,
    placeholder: `${commanString.enter} ${commanString.mobile}`,
    required: `${commanString.Please_enter} ${commanString.mobile}`,
  },
  {
    id: 13,
    label_class: 'form-label',
    label_name: `${commanString.whatsapp_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.whatsapp_mobile}`,
    placeholder: `${commanString.enter} ${commanString.whatsapp_mobile}`,
    required: `${commanString.Please_enter} ${commanString.whatsapp_mobile}`,
  },
  {
    id: 14,
    label_class: 'form-label',
    label_name: `${commanString.parent_mobile}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.parent_mobile}`,
    placeholder: `${commanString.enter} ${commanString.parent_mobile}`,
    required: `${commanString.Please_enter} ${commanString.parent_mobile}`,
  },
  {
    id: 18,
    label_class: 'form-label',
    label_name: `${commanString.personal_email}`,
    input_class: 'form-control',
    type: 'email',
    name: `${commanString.personal_email}`,
    placeholder: `${commanString.enter} ${commanString.personal_email}`,
    required: `${commanString.Please_enter} ${commanString.personal_email}`,
  },
  {
    id: 16,
    label_class: 'form-label',
    label_name: `${commanString.adhar_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.adhar_card_number}`,
    placeholder: `${commanString.enter} ${commanString.adhar_card_number}`,
    required: `${commanString.Please_enter} ${commanString.adhar_card_number}`,
  },
  {
    id: 17,
    label_class: 'form-label',
    label_name: `${commanString.pan_card_number}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.pan_card_number}`,
    placeholder: `${commanString.enter} ${commanString.pan_card_number}`,
    required: `${commanString.Please_enter} ${commanString.pan_card_number}`,
  },
]

export const AddressDetailform = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.address_1}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.address_1}`,
    placeholder: `${commanString.enter} ${commanString.address_1}`,
    required: `${commanString.Please_enter} ${commanString.address_1}`,
    permanent_address: 'Permanent Address',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.address_2}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.address_2}`,
    placeholder: `${commanString.enter} ${commanString.address_2}`,
    required: `${commanString.Please_enter} ${commanString.address_2}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.city}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.city}`,
    placeholder: `${commanString.enter} ${commanString.city}`,
    required: `${commanString.Please_enter} ${commanString.city}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.state_region}`,
    input_class: 'form-control',
    type: 'text',
    name: `${commanString.state_region}`,
    placeholder: `${commanString.enter} ${commanString.state_region}`,
    required: `${commanString.Please_enter} ${commanString.state_region}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.postal_code}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.postal_code}`,
    placeholder: `${commanString.enter} ${commanString.postal_code}`,
    required: `${commanString.Please_enter} ${commanString.postal_code}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.country}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.country}`,
    placeholder: `${commanString.enter} ${commanString.country}`,
    required: `${commanString.Please_enter} ${commanString.country}`,
    option: [
      { value: `${commanString.indian}`, label: `${commanString.indian}` },
    ],
  },
]

export const inputBox = [
  {
    id: 1,
    type: 'checkbox',
    value: 'checked',
  },
  {
    id: 2,
    type: 'checkbox',
    value: 'checked',
  },
  {
    id: 3,
    type: 'checkbox',
    value: 'checked',
  },
]
