const commanString = {
  role: 'Role',
  permission: 'Permission',
  setup_role_permission: 'Setup Role Permission',
  user_info: 'User Info',
  employee: 'Employee',
  assets_type: 'Assets Type',
  assets_application: 'Assets Application',
  leave_type: 'Leave Type',
  leave_application: 'Leave Application',
  holiday_list: 'Holiday List',
  holiday_type: 'Holiday Type',
  company_document: 'Company Document',
  company_policy: 'Company Policy',
  apply: 'Apply',
  search_by_user_or_email: 'Search by user or email',
  have_balance: 'Have Balance',
  kyc_verified: 'KYC Verified',
  search: 'search',
  filter: 'Filter',
  cancle: 'Cancel',
  export: 'Export',
  status: 'Status',
  show: 'Show',
  order: 'Order',
  asc_order: 'ASC',
  desc_order: 'DESC',
  submit: 'Submit',
  create: 'Create',
  user: 'User',
  reset: 'Reset',
  save: 'Save',
  copy: 'Copy',
  csv: 'CSV',
  excel: 'Excel',
  copied: 'Copied',
  to_clipboard: 'to clipboard',
  company: 'Company',
  gender: 'Gender',
  male: 'Male',
  female: 'Female',
  birth_day: 'Birth Date',
  salary: 'Salary',
  start_date: 'Start Date',
  there_are_no_record: 'There are no records found',
  view: 'View',
  invoice: 'Invoice',
  print: 'Print',
  bill_for: 'Bill For',
  issue: 'Issue',
  due: 'Due',
  total: 'Total',
  order_id: 'Order ID',
  amount: 'Amount',
  browser: 'Browser',
  ip: 'IP',
  time: 'Time',
  immence_2022: '2022-immence',
  immence: 'immence',
  administrator: 'Administrator',
  abu_bin_ishityak: 'Abu Bin Ishityak',
  profile: 'Profile',
  account_setting: 'Account Setting',
  login_activity: 'Login Activity',
  sign_out: 'Sign Out',
  this_field_is_required: 'This field is required',
  am: 'AM',
  pm: 'PM',
  month:
    'January,February,March,April,May,June,July,August,September,October,November,December',
  dashboard: 'Dashboard',
  user_manage: 'User Manage',
  assets: 'Assets',
  leave: 'Leave',
  holiday: 'Holiday',
  policy: 'policy',
  login: 'Login',
  sign_in: 'Sign In',
  forgot_password: 'Forgot Password',
  success: 'Success',
  conform: 'Conform ',
  error_page: 'Error Page',
  classic: 'Classic',
  modern: 'Modern',
  organization_meta_id: `Organization Meta Id`,
  number: 'number',
  Please_enter: 'Please enter',
  name: 'Name',
  description: 'Description',
  isactive: 'Is Active',
  select: 'Select',
  active: 'Active',
  inactive: 'In Active',
  isdelete: 'Is Delete',
  is_not_deleted: 'Is Not Deleted',
  employee_id: 'Employee Id',
  assetsType_id: 'AssetsType Id',
  end_date: 'End Date',
  attachment: 'Attachment',
  remark: 'Remark',
  pending: 'Pending',
  suspend: 'suspend',
  updated_by: 'Updated By',
  created_by: 'Created By',
  leave_type_id: 'Leave Type Id',
  approved: 'Approved',
  approved_by: 'Approved By',
  reject: 'Reject',
  type: 'Type',
  title: 'Title',
  slug: 'Slug',
  content: 'Content',
  user_id: 'User Id',
  role_id: 'Role Id',
  code: 'Code',
  start_at: 'Start At',
  end_at: 'End At',
  note: 'Notes',
  avatr: 'Avatar',
  first_name: 'First Name',
  last_name: 'Last Name',
  middle_name: 'Middle Name',
  department: 'Department',
  mobile: 'Mobile Number',
  whatsapp_mobile: 'Whatsapp Mobile Number',
  parent_mobile: 'Parent Mobile Number',
  adhar_card_number: 'Aadhar Card Number',
  pan_card_number: 'Pan Card Number',
  last_login: 'Last Login',
  intro: 'Intro',
  swift_time: 'Swift Time',
  admin: 'Admin',
  registered_at: 'Registered At',
  term_condition: 'Terms &amp; Condition',
  privacy: 'Privacy',
  help: 'Help',
  current_address: 'Current Address',
  permenent_address: 'Permanent Address',
  address_detail: 'Address Detail',
  education: ' Education',
  country: 'Country',
  height: 'Height',
  can_not_login: 'Cannot login with credentials',
  reset_password: 'Reset password',
  if_you_forgot_your:
    'If you forgot your password, well, then we’ll email you instructions to reset your password.',
  unable_to_login: ' Unable to login with credentials',
  email: 'Email',
  personal_email: 'Personal Email',
  return_to_login: 'Return to login',
  access_immence_using_email_pass:
    'Access immence using your email and passcode.',
  forget_code: 'Forgot Code?',
  you_can_now_sign_in: 'You can now sign in with your new password',
  welcome_to_immence: 'Welcome to immence',
  delete: 'Delete',
  enter: 'Enter',
  next: 'Next',
  previous: 'Previous',
  user_create: 'User Create',
  personal_detail: 'Personal Detail',
  number_email: 'Number & Email',
  office_detail: 'Office Detail',
  other: 'Others',
  thank_you_for_submitting_form: 'Thank you for submitting form',
  hr: 'Hr',
  edit: 'Edit',
  employee_code: 'Employee Code',
  designation: 'Designation',
  blood_group: 'Blood Group',
  blood_group_name: 'A,A+,B,B+,O,O+',
  nationality: 'Nationality',
  indian: 'Indian',
  address_1: 'Address 1',
  address_2: 'Address 2',
  city: 'City',
  state_region: 'State/Region',
  postal_code: 'Postal/Zip Code',
  same_as_permenent_address: 'Same As Permenent Address',
  a: 'A',
  a_plus: 'A+',
  b: 'B',
  b_plus: 'B+',
  o: 'O',
  o_plus: 'O+',
  add: 'Add',
}

export default commanString
