export const holidaytypeform = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: 'Organization Meta Id',
    input_class: 'form-control',
    type: 'number',
    name: 'Organization-meta-id',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: 'Name',
    input_class: 'form-control',
    type: 'text',
    name: 'name',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: 'Description',
    input_class: 'form-control',
    type: 'text',
    name: 'Description',
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: 'Date',
    input_class: 'form-control',
    type: 'date',
    name: 'date',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: 'Type',
    input_class: 'form-control',
    type: 'number',
    name: 'type',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: 'Approved Date',
    input_class: 'form-control',
    type: 'date',
    name: 'Approved Date',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: 'IsActive',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'Active', label: 'Active' },
      { value: 'InActive', label: 'InActive' },
    ],
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: 'IsDelete',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'IsDeleted', label: 'IsDeleted' },
      { value: 'IsNotDeleted', label: 'IsNotDeleted' },
    ],
  },
]
export const holidaytypetable = [
  {
    id: 1,
    name: 'Organization Meta Id',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 2,
    name: 'Name',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 3,
    name: 'Date',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 4,
    name: 'Type',
    size: 'sm',
    className: 'sub-text',
  },

  {
    id: 5,
    name: 'Approved Date',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 6,
    name: 'created by',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 6,
    name: 'IsActive',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 7,
    name: 'IsDelete',
    size: 'md',
    className: 'sub-text',
  },
]
