import commanString from '../../../utils/String'

export const leaveAppForm = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: `${commanString.employee_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.employee_id}`,
    required: `${commanString.Please_enter} ${commanString.employee_id}`,
    placeholder: `${commanString.enter} ${commanString.employee_id}`,
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: `${commanString.leave_type_id}`,
    input_class: 'form-control',
    type: 'number',
    name: `${commanString.leave_type_id}`,
    required: `${commanString.Please_enter} ${commanString.leave_type_id}`,
    placeholder: `${commanString.enter} ${commanString.leave_type_id}`,
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: `${commanString.start_date}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.start_date}`,
    required: `${commanString.Please_enter} ${commanString.start_date}`,
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: `${commanString.end_date}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.end_date}`,
    required: `${commanString.Please_enter} ${commanString.end_date}`,
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: `${commanString.attechment}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.date}`,
    required: `${commanString.Please_enter} ${commanString.attechment}`,
    placeholder: `${commanString.enter} ${commanString.attechment}`,
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: `${commanString.remark}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.remark}`,
    required: `${commanString.Please_enter} ${commanString.remark}`,
    placeholder: `${commanString.enter} ${commanString.remark}`,
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: `${commanString.status}`,
    input_class: 'form-control',
    type: 'select',
    name: `${commanString.status}`,
    option: [
      { value: `${commanString.pending}`, label: `${commanString.pending}` },
      { value: `${commanString.approved}`, label: `${commanString.approved}` },
      { value: `${commanString.reject}`, label: `${commanString.reject}` },
    ],
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: `${commanString.approved} ${commanString.date}`,
    input_class: 'form-control',
    type: `${commanString.date}`,
    name: `${commanString.approved} ${commanString.date}`,
    required: `${commanString.Please_enter} ${commanString.approved} ${commanString.date}`,
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: `${commanString.updated_by}`,
    input_class: 'form-control',
    type: `${commanString.text}`,
    name: `${commanString.updated_by}`,
    required: `${commanString.Please_enter} ${commanString.updated_by} `,
    placeholder: `${commanString.enter} ${commanString.updated_by}`,
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: `${commanString.isactive}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.active}`, label: `${commanString.active}` },
      { value: `${commanString.inactive}`, label: `${commanString.inactive}` },
    ],
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: `${commanString.isdelete}`,
    input_class: 'form-control',
    type: 'select',
    name: 'select',
    option: [
      { value: `${commanString.isdelete}`, label: `${commanString.isdelete}` },
      {
        value: `${commanString.is_not_deleted}`,
        label: `${commanString.is_not_deleted}`,
      },
    ],
  },
]

export const leaveAppTable = [
  {
    id: 1,
    name: `${commanString.employee_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 2,
    name: `${commanString.leave_type_id}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 3,
    name: `${commanString.start_date}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 4,
    name: `${commanString.end_date}`,
    className: `${commanString.sub_text}`,
  },

  {
    id: 5,
    name: `${commanString.status}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 6,
    name: `${commanString.approved_by}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 7,
    name: `${commanString.updated_by}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 8,
    name: `${commanString.isactive}`,
    className: `${commanString.sub_text}`,
  },
  {
    id: 9,
    name: `${commanString.isdelete}`,
    className: `${commanString.sub_text}`,
  },
]
