export const leaveappform = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: 'Employe  Id',
    input_class: 'form-control',
    type: 'number',
    name: 'employeid',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: 'Leave Type Id',
    input_class: 'form-control',
    type: 'number',
    name: 'leave-type-id',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: 'Start Date',
    input_class: 'form-control',
    type: 'date',
    name: 'start-date',
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: 'End Date',
    input_class: 'form-control',
    type: 'date',
    name: 'end-date',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: 'Attachment',
    input_class: 'form-control',
    type: 'text',
    name: 'attachment',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: 'Remark',
    input_class: 'form-control',
    type: 'text',
    name: 'remark',
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: 'Status',
    input_class: 'form-control',
    type: 'select',
    name: 'status',
    option: [
      { value: 'Panding', label: 'Panding' },
      { value: 'Approved', label: 'Approved' },
      { value: 'Reject', label: 'Reject' },
    ],
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: 'Approved  Date',
    input_class: 'form-control',
    type: 'date',
    name: 'Approved -date',
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: 'Update By',
    input_class: 'form-control',
    type: 'text',
    name: 'update-by',
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: 'IsActive',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'Active', label: 'Active' },
      { value: 'InActive', label: 'InActive' },
    ],
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: 'IsDelete',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'IsDeleted', label: 'IsDeleted' },
      { value: 'IsNotDeleted', label: 'IsNotDeleted' },
    ],
  },
]

export const leaveapptable = [
  {
    id: 1,
    name: 'Employe Id',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 2,
    name: 'Leave Type id',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 3,
    name: 'Start Date',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 4,
    name: 'End Date',
    size: 'sm',
    className: 'sub-text',
  },

  {
    id: 5,
    name: 'Status',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 6,
    name: 'Aproved By',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 7,
    name: 'Update By',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 8,
    name: 'IsActive',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 9,
    name: 'IsDelete',
    size: 'sm',
    className: 'sub-text',
  },
]
