export const employe = [
  {
    id: 1,
    label_class: 'form-label',
    label_name: 'User Id',
    input_class: 'form-control',
    type: 'number',
    name: 'user-id',
  },
  {
    id: 2,
    label_class: 'form-label',
    label_name: 'Role Id',
    input_class: 'form-control',
    type: 'number',
    name: 'role-id',
  },
  {
    id: 3,
    label_class: 'form-label',
    label_name: 'Created By',
    input_class: 'form-control',
    type: 'number',
    name: 'createdby',
  },
  {
    id: 4,
    label_class: 'form-label',
    label_name: 'Updated By',
    input_class: 'form-control',
    type: 'number',
    name: 'updated-by',
  },
  {
    id: 5,
    label_class: 'form-label',
    label_name: 'Code',
    input_class: 'form-control',
    type: 'number',
    name: 'code',
  },
  {
    id: 6,
    label_class: 'form-label',
    label_name: 'Status',
    input_class: 'form-control',
    type: 'select',
    name: 'status',
    option: [
      { value: 'Active', label: 'Active' },
      { value: 'Pending', label: 'Pending' },
      { value: 'Suspend', label: 'Suspend' },
    ],
  },
  {
    id: 7,
    label_class: 'form-label',
    label_name: 'Starts At',
    input_class: 'form-control',
    type: 'number',
    name: 'start-at',
  },
  {
    id: 8,
    label_class: 'form-label',
    label_name: 'Ends At',
    input_class: 'form-control',
    type: 'number',
    name: 'ends-at',
  },
  {
    id: 9,
    label_class: 'form-label',
    label_name: 'Notes',
    input_class: 'form-control',
    type: 'number',
    name: 'start-at',
  },
  {
    id: 10,
    label_class: 'form-label',
    label_name: 'IsActive',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'Active', label: 'Active' },
      { value: 'InActive', label: 'InActive' },
    ],
  },
  {
    id: 11,
    label_class: 'form-label',
    label_name: 'IsDelete',
    input_class: 'form-control',
    type: 'select',
    name: 'type',
    option: [
      { value: 'IsDeleted', label: 'IsDeleted' },
      { value: 'IsNotDeleted', label: 'IsNotDeleted' },
    ],
  },
]

export const employet = [
  {
    id: 1,
    name: 'User Id',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 2,
    name: 'Role Id',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 3,
    name: 'Created By',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 4,
    name: 'Updated By',
    size: 'sm',
    className: 'sub-text',
  },

  {
    id: 6,
    name: 'Code',
    size: 'sm',
    className: 'sub-text',
  },
  {
    id: 7,
    name: 'Status',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 8,
    name: 'IsActive',
    size: 'md',
    className: 'sub-text',
  },
  {
    id: 9,
    name: 'IsDelete',
    size: 'md',
    className: 'sub-text',
  },
]
